steps:
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/libralog-backend/libralog-backend:1', '.' ]
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/libralog-backend/libralog-backend:1']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'libralog-backend', '--image', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/libralog-backend/libralog-backend:1', '--region', 'southamerica-east1']
images:
- 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/libralog-backend/libralog-backend'
