version: "3"

services:
  pg:
    image: "bitnami/postgresql:latest"
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=libralog
      - POSTGRESQL_PASSWORD=libralogpass
      - POSTGRESQL_DATABASE=libralog
